### ISSUE TITLE
udpxy不能启动

### ISSUE THREAD

**Issue by kongjun0** [ntlf9t/openwrt_update#1]
在服务里开启，然后SSH命令  PS看进程也看不到启动。

**Comment by ntlf9t** [comment]
udpxy有单独的luci启动设置界面的

**Comment by kongjun0** [comment]
在luci里已经配置，就是不能用才ps命令查看，没运行。

**Comment by ntlf9t** [comment]
udpxy勾选启动，后台查看运行正常。还有问题尝试更新到最新版本（不保存配置升级）

**Comment by kongjun0** [comment]
又重新测试，配置界面已经勾选，后台PS看不到进程，也重新刷机过，

内核版本 | 4.14.123
-- | --

**Comment by kongjun0** [comment]
penWrt
主机型号 | Intel(R) Celeron(R) CPU 3215U @ 1.70GHz : 2 Core 2 Thread
CPU信息 | 1696.074 MHz
CPU温度 | +100.0°C (high = +100.0°C, crit = +100.0°C)
固件版本 | OpenWrt R9.x.x By Lean Mod3.1.27 By dz / LuCI Master (git-19.132.29854-70347d8)
内核版本 | 4.14.123
本地时间 | Sat Jun 22 20:35:22 2019
运行时间 | 0h 4m 17s
平均负载 | 0.07, 0.05, 0.01
CPU 使用率（%）

**Comment by kongjun0** [comment]
CFG01F55F
启用Respawn详细状态Bind IP/Interface
br-lan
端口
8888
Source IP/Interface
eth1
最大连接数
10
日志文件
Buffer size
Buffer messages
Buffer time
Nice increment
Multicast subscription renew

**Comment by kongjun0** [comment]
PID USER       VSZ STAT COMMAND
    1 root      1176 S    /sbin/procd
    2 root         0 SW   [kthreadd]
    4 root         0 IW<  [kworker/0:0H]
    6 root         0 IW<  [mm_percpu_wq]
    7 root         0 SW   [ksoftirqd/0]
    8 root         0 IW   [rcu_sched]
    9 root         0 IW   [rcu_bh]
   10 root         0 SW   [migration/0]
   11 root         0 SW   [cpuhp/0]
   12 root         0 SW   [cpuhp/1]
   13 root         0 SW   [migration/1]
   14 root         0 SW   [ksoftirqd/1]
   15 root         0 IW   [kworker/1:0]
   16 root         0 IW<  [kworker/1:0H]
   17 root         0 IW   [kworker/u4:1]
   34 root         0 IW   [kworker/0:1]
  199 root         0 SW   [oom_reaper]
  239 root         0 IW<  [writeback]
  242 root         0 SW   [kcompactd0]
  243 root         0 IW<  [crypto]
  244 root         0 IW<  [kintegrityd]
  245 root         0 IW<  [kblockd]
  751 root         0 IW<  [ata_sff]
  772 root         0 IW<  [watchdogd]
  892 root         0 SW   [kswapd0]
  987 root         0 IW<  [pencrypt]
  989 root         0 IW<  [pdecrypt]
 1064 root         0 IW<  [acpi_thermal_pm]
 1116 root         0 SW   [scsi_eh_0]
 1117 root         0 IW<  [scsi_tmf_0]
 1118 root         0 IW<  [vmw_pvscsi_wq_0]
 1128 root         0 SW   [scsi_eh_1]
 1131 root         0 IW   [kworker/u4:3]
 1142 root         0 IW<  [scsi_tmf_1]
 1146 root         0 SW   [scsi_eh_2]
 1147 root         0 IW<  [scsi_tmf_2]
 1216 root         0 IW   [kworker/1:2]
 1218 root         0 IW<  [ipv6_addrconf]
 1229 root         0 IW<  [ext4-rsv-conver]
 1335 root         0 IW<  [kworker/0:1H]
 1346 root         0 IW<  [ext4-rsv-conver]
 1605 root       860 S    /sbin/ubusd
 1607 root      1076 S    /bin/ash --login
 1724 root         0 IW<  [cifsiod]
 1725 root         0 IW<  [cifsoplockd]
 1729 root         0 IW<  [rpciod]
 1731 root         0 IW<  [xprtiod]
 1828 root         0 IW<  [ixgbe]
 1834 root         0 IW<  [ixgbevf]
 1862 root         0 IW<  [bond0]
 1898 root         0 IW<  [nfsiod]
 2049 root         0 IW<  [cryptodev_queue]
 2441 root         0 IW<  [cfg80211]
 3132 root         0 IW<  [kworker/1:1H]
 3633 root       948 S    /sbin/logd -S 64
 3648 root      1132 S    /sbin/rpcd -s /var/run/ubus.sock -t 30
 3721 root       864 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
 3897 root      1288 S    /sbin/netifd
 3960 root      1052 S    /usr/sbin/odhcpd
 4075 root      1064 S    udhcpc -p /var/run/udhcpc-eth1.pid -s /lib/netifd/dh
 4076 root       796 S    odhcp6c -s /lib/netifd/dhcpv6.script -P0 -t120 eth1
 5007 root      1072 S    /usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -
 5060 root       916 S    /usr/sbin/vsftpd -olisten_address=0.0.0.0 -olisten=Y
 5322 root       972 S    /usr/sbin/nlbwmon -o /var/lib/nlbwmon -i 24h -r 30s
 5531 dnsmasq   1112 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.cfg01411c
 6310 root     24552 S    /usr/sbin/smbd -F
 6362 root      1064 S<   /usr/sbin/ntpd -n -N -l -S /usr/sbin/ntpd-hotplug -p
 6484 root      1068 S    /usr/sbin/crond -f -c /etc/crontabs -l 5
 6621 root     21728 S    {smbd-notifyd} /usr/sbin/smbd -F
 6622 root     21720 S    {cleanupd} /usr/sbin/smbd -F
 6999 root      3996 S    /usr/bin/ttyd -i br-lan /bin/login
 7437 root       740 S    /usr/bin/wsdd2 -w
 7632 root         0 IW   [kworker/0:2]
10252 root         0 RW   [kworker/u4:0]
10256 root       980 R    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p
10272 root      1076 S    -ash
10479 root         0 Z    [set_kernel_time]

**Comment by kongjun0** [comment]
OpenWrt
--
主机型号 | Intel(R) Celeron(R) CPU 3215U @ 1.70GHz : 2 Core 2 Thread
CPU信息 | 1696.074 MHz
CPU温度 | +100.0°C +100.0°C
固件版本 | OpenWrt R9.x.x By Lean Mod3.1.35 By dz / LuCI Master (git-19.132.29854-70347d8)
内核版本 | 4.14.128
本地时间 | Sat Jun 22 21:02:13 2019
运行时间 | 0h 8m 31s
平均负载 | 0.04, 0.03, 0.00
CPU 使用率（%） | 0.00%
