### ISSUE TITLE
ShadowSocksR 服务端 無法使用  

### ISSUE THREAD

**Issue by rsw7316** [ntlf9t/openwrt_update#2]
在v3.1.22可正常使用 (3.1.28  3.1.29都無法使用)

  | ssr | 10240 | AES-256-CFB | origin | plain

**Comment by ntlf9t** [comment]
测试正常，自己进行看看是不是参数多敲了空格之类的错误

**Comment by rsw7316** [comment]
Tue Jun 11 20:05:47 2019 kern.info /usr/bin/ssr-server[12241]: UDP relay enabled
Tue Jun 11 20:05:47 2019 kern.info /usr/bin/ssr-server[12241]: initializing ciphers... aes-256-cfb
Tue Jun 11 20:05:47 2019 kern.info /usr/bin/ssr-server[12241]: tcp port reuse enabled
Tue Jun 11 20:05:47 2019 kern.info /usr/bin/ssr-server[12241]: udp port reuse enabled
Tue Jun 11 20:05:47 2019 kern.info /usr/bin/ssr-server[12241]: listening at [::]:10240
Tue Jun 11 20:05:47 2019 kern.info /usr/bin/ssr-server[12241]: running from root user
會是ipv6關係嗎?[::]:10240 在前面版本會出現[0.0.0.0]:1024

**Comment by ntlf9t** [comment]
是的为了支持IPV6我把参数由0.0.0.0改成::了可能是这个问题
