### ISSUE TITLE
支持新版本

### ISSUE THREAD

**Issue by fuqiang03** [ntlf9t/openwrt_update#4]
op的主库问题可不少，前几天我跪在了工具链上（添加指令集）。luci兼容问题（一般是shell脚本无响应），由于gcc升级部分文件编译时候报错（我用的是gcc9.1 glibc），总之是问题多多啊。
能从大神这学点经验就好了。
https://github.com/tano-systems/luci-app-ttyd 
[luci-app-ttyd.zip](https://github.com/ntlf9t/openwrt_update/files/3443416/luci-app-ttyd.zip)
仅适用在18.06 1900acs上

**Comment by ntlf9t** [comment]
我也是咸鱼，一直灵车翻滚

**Comment by fuqiang03** [comment]
如果软路由性能够 可以做个服务期 干什么都方便

**Comment by fuqiang03** [comment]
openwrt 18.06 openssl 有跪下了
哎  我就服了 稳定版的 都这样了

**Comment by fuqiang03** [comment]
放弃主库了?

**Comment by ntlf9t** [comment]
移动到后面去了

**Comment by fuqiang03** [comment]
@ntlf9t 大神可否给个imq 4.14内核的完整补丁吗
