### ISSUE TITLE
固件带的OSCAM11534版本，不能请求DVBAPI请求，不解密

### ISSUE THREAD

**Issue by kongjun0** [ntlf9t/openwrt_update#6]
请查找下，换成11380可正常使用

**Comment by kongjun0** [comment]
2019/08/08 13:59:21 00000000 s     (main) Host name      = OpenWrt
2019/08/08 13:59:21 00000000 s     (main) Release        = 4.9.186
2019/08/08 13:59:21 00000000 s     (main) Version        = #0 SMP Sun Apr 28 04:32:46 2019
2019/08/08 13:59:21 00000000 s     (main) Machine        = x86_64
2019/08/08 13:59:21 00000000 s     (main) creating pidfile /tmp/.oscam/oscam.pid with pid 6278
2019/08/08 13:59:21 00000000 s      (emu) OSCam-Emu version 789
2019/08/08 13:59:21 00000000 s   (config) userdb reloaded: 3 accounts loaded, 0 expired, 0 disabled
2019/08/08 13:59:21 00000000 s     (main) signal handling initialized
2019/08/08 13:59:21 00000000 s      (net) camd33: initialized (fd=3, port=44444, ip=127.0.0.1)
2019/08/08 13:59:21 00000000 s      (net) cccam: initialized (fd=4, port=12000)
2019/08/08 13:59:21 00000000 s   (reader) emulator [emu] creating thread for device emulator
2019/08/08 13:59:21 00000000 s   (reader) Reader-1 [smargo] creating thread for device /dev/ttyUSB0
2019/08/08 13:59:21 00000000 s     (main) waiting for local card init
2019/08/08 13:59:21 1CAD91D1 r      (emu) Stream key delayer initialized
2019/08/08 13:59:21 1CAD91D1 r      (emu) Stream relay server initialized
2019/08/08 13:59:21 1CAD91D1 r   (reader) emulator [emu] Reader initialized (device=emulator, detect=cd, mhz=357, cardmhz=357)
2019/08/08 13:59:21 1CAD91D1 r   (reader) emulator [emu] card detected
2019/08/08 13:59:21 00000000        (emu) INFO: FFDecsa parallel mode = 128
2019/08/08 13:59:21 16B37BDA h    (webif) webif: decompressed 200929 bytes back into 433072 bytes
2019/08/08 13:59:21 16B37BDA h    (webif) HTTP Server running. ip=0.0.0.0 port=8888
2019/08/08 13:59:21 77667ED8 r   (reader) Reader-1 [smargo] Reader initialized (device=/dev/ttyUSB0, detect=cd, mhz=369, cardmhz=1200)
2019/08/08 13:59:22 77667ED8 r   (reader) Reader-1 [smargo] card detected
2019/08/08 13:59:22 1CAD91D1 r   (reader) emulator [emu] found card system emu
2019/08/08 13:59:22 1CAD91D1 r   (reader) emulator [emu] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max allotted of 1
2019/08/08 13:59:22 1CAD91D1 r      (emu) Key file not found in: /etc/oscam
2019/08/08 13:59:22 1CAD91D1 r      (emu) Cannot open key file path: /var/keys
2019/08/08 13:59:22 1CAD91D1 r      (emu) Total keys in memory: W:0 V:0 N:0 I:0 S:0 F:0 P:0 D:0 T:0 A:0
2019/08/08 13:59:24 77667ED8 r   (reader) Reader-1 [smargo] ATR: 3B 7F 12 00 00 44 56 4E 20 54 45 43 48 20 52 65 76 35 33 76 
2019/08/08 13:59:26 77667ED8 r   (reader) Reader-1 [smargo] DVN Jetcas version 5.3 card detect
2019/08/08 13:59:26 77667ED8 r   (reader) Reader-1 [smargo] serial step1,SN
2019/08/08 13:59:26 77667ED8 r   (reader)   99 41 01 00 00 95 95 84 
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [smargo] type: jet, caid: 4A30, serial: 11043108860810597764, hex serial: 9941010000959584, boxkey: 787C45F99C3E668F63C62AFDCFFE11BEC5741CB02226262635292C37947BEF74
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [smargo] found card system dvn
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn] THIS WAS A SUCCESSFUL START ATTEMPT No  1 out of max allotted of 1
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn] entitlements for (4A30:000000):
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0001  date: 2019/03/11 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0072  date: 2013/07/24 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0067  date: 2013/07/24 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0078  date: 2013/07/24 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0068  date: 2013/07/24 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0074  date: 2013/07/24 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 007D  date: 2013/07/24 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0073  date: 2013/07/24 - 2030/12/31
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 006C  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:28 77667ED8 r   (reader) Reader-1 [dvn]     chid: 006D  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 007F  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0076  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 006E  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 006F  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0070  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 007E  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 007C  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0071  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0069  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0079  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0077  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 006A  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 007A  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 006B  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0075  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 003F  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0040  date: 2013/12/04 - 2014/11/30
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0004  date: 2018/01/01 - 2030/12/31
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 000D  date: 2019/03/11 - 2020/03/31
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0065  date: 2019/03/11 - 2020/03/31
2019/08/08 13:59:29 77667ED8 r   (reader) Reader-1 [dvn]     chid: 0064  date: 2019/03/11 - 2020/03/31
2019/08/08 13:59:30 00000000 s     (main) init for all local cards done
2019/08/08 13:59:30 00000000 s (emmcache) loading emmcache disabled since no reader is using it!
2019/08/08 13:59:30 00000000 s (emmcache) loading emmstats disabled since no reader is using it!
2019/08/08 13:59:30 00000000 s (anticasc) anti cascading disabled
2019/08/08 13:59:30 5A662C7E c   (client) plain dvbapi-client granted (anonymous, au=off)
2019/08/08 13:59:30 5A662C7E c   (dvbapi) dvbapi channelcache loaded from /etc/oscam/oscam.ccache
2019/08/08 13:59:30 5A662C7E c   (dvbapi) Using TCP listen socket, API forced to DVBAPIv3 (0), userconfig boxtype: 11
2019/08/08 14:00:22 5A662C7E c   (dvbapi) Client connected: 'Tvheadend 8ff1555~openwrt' (protocol version = 2)
2019/08/08 14:45:10 5A662C7E c   (dvbapi) Client connected: 'Tvheadend 4.3-1792~g466a014-dirty' (protocol version = 2)
2019/08/08 14:45:23 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 0415 PROVID: 000000 
2019/08/08 14:45:23 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0419 PROVID: 000000 
2019/08/08 14:45:23 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:45:23 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:45:26 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 0068 (4A30@000000:0068 unknown)
2019/08/08 14:45:34 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 08A7 PROVID: 000000 
2019/08/08 14:45:34 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0027 PROVID: 000000 
2019/08/08 14:45:34 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:45:34 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:45:36 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 00DD (4A30@000000:00DD unknown)
2019/08/08 14:45:39 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 08B1 PROVID: 000000 
2019/08/08 14:45:39 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0026 PROVID: 000000 
2019/08/08 14:45:39 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:45:39 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:45:44 5A662C7E c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!
2019/08/08 14:46:06 5A662C7E c        (-) -- Skipped 4 duplicated log lines --
2019/08/08 14:46:06 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 00DE (4A30@000000:00DE unknown)
2019/08/08 14:48:00 5A662C7E c   (dvbapi) Client connected: 'Tvheadend 4.3-1792~g466a014-dirty' (protocol version = 2)
2019/08/08 14:48:59 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 0415 PROVID: 000000 
2019/08/08 14:48:59 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0419 PROVID: 000000 
2019/08/08 14:48:59 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:48:59 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:49:02 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 0068 (4A30@000000:0068 unknown)
2019/08/08 14:49:04 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 0965 PROVID: 000000 
2019/08/08 14:49:04 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0021 PROVID: 000000 
2019/08/08 14:49:04 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:49:04 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:49:06 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 00F0 (4A30@000000:00F0 unknown)
2019/08/08 14:49:10 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 096F PROVID: 000000 
2019/08/08 14:49:10 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0029 PROVID: 000000 
2019/08/08 14:49:10 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:49:10 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:49:13 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 00F1 (4A30@000000:00F1 unknown)
2019/08/08 14:49:15 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 0979 PROVID: 000000 
2019/08/08 14:49:15 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 002F PROVID: 000000 
2019/08/08 14:49:15 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:49:15 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:49:17 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 00F2 (4A30@000000:00F2 unknown)
2019/08/08 14:49:20 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 08A7 PROVID: 000000 
2019/08/08 14:49:20 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0027 PROVID: 000000 
2019/08/08 14:49:20 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:49:20 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:49:23 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 00DD (4A30@000000:00DD unknown)
2019/08/08 14:49:26 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 4A30 ECM_PID: 08B1 PROVID: 000000 
2019/08/08 14:49:26 5A662C7E c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 4AB0 ECM_PID: 0026 PROVID: 000000 
2019/08/08 14:49:26 5A662C7E c   (dvbapi) Demuxer 0 found 2 ECM pids and 2 STREAM pids in CA PMT
2019/08/08 14:49:26 5A662C7E c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
2019/08/08 14:49:31 5A662C7E c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!
2019/08/08 14:49:41 5A662C7E c        (-) -- Skipped 1 duplicated log lines --
2019/08/08 14:50:03 5A662C7E c        (-) -- Skipped 5 duplicated log lines --
2019/08/08 14:50:03 5A662C7E c   (dvbapi) Demuxer 0 stopped descrambling for program 00DE (4A30@000000:00DE unknown)

**Comment by kongjun0** [comment]
官方OSCAM正常

**Comment by ntlf9t** [comment]
nx111新代码问题他修了，下个版本更新

**Comment by kongjun0** [comment]
nx111修复过还不行

**Comment by ntlf9t** [comment]
最新修过了，不行就退版本

**Comment by kongjun0** [comment]
> 最新修过了，不行就退版本

N大原话：引用“是否你的编译方法有问题，只需在oscam目录下执行make即可。 '

**Comment by kongjun0** [comment]
问题已经找到，是oscam.dvbapi中的 I:0 这行的问题，新旧代码可能对这行的理解不同，新代码表示忽略所有，旧代码表示忽略caid为0的节目。你注意N大OS代码这个地方就行，于2019年8月15号，N大帮忙查找问题，给出的问题所在，你再下个版本修复即可。


我不是来找茬，因为我用你的软路由固件很全面，我只是想让OSCAM更完美更稳定而已，让更多让你不走弯路，否则我自己搞定我自己的，我管别人怎么用！另外TVHEADEND版本能否用最新版本，我发现目前这个版本天栢卡只能用DVBAPI不能用CCCAM，我另外平台用最新版本已经可以用CCCAM了

**Comment by ntlf9t** [comment]
收到

**Comment by kongjun0** [comment]
索尼cxd2837的dvb驱动能否下个版本加上，或者4.19.?内核的能否带上tvheadend

**Comment by kongjun0** [comment]
mn88472驱动默认的不识别，默认驱动里不能使用，需要选用dvblatest驱动包才可以正常识别。能否修复

**Comment by ntlf9t** [comment]
mn88472加了 oscam.dvbapi配置文件修了

**Comment by kongjun0** [comment]
> mn88472加了oscam.dvbapi配置文件修了

谢谢
