### ISSUE TITLE
32位的管理地址是192.168.1.1吗？

### ISSUE THREAD

**Issue by babylife** [ntlf9t/openwrt_update#9]
描述上是10.1 ，但是ip show的话，还是192.168.1.1 刚玩X86固件，忘大神解惑
管理地址：192.168.1.1 从mod3.1.0.1开始改为192.168.10.1 登陆密码:password

**Comment by kongjun0** [comment]
都试下不就知道了，软路由楼主的固件只绑定了1个LAN口，你多换几个口试试

**Comment by babylife** [comment]
确认是10.1 close
